### PR TITLE
Fix corrupt catalog cache issue when plugins were installed with old CLI

### LINKED ISSUE #312: A warning is shown when installing plugins with older cli plugin and persists with new Tanzu CLI
**Bug description**

1. Install `management-cluster v0.25.4` plugin with `tanzu-cli v0.25.4`.
2. Create management-cluster
3. Install independent Tanzu CLI v0.90.0-alpha.1
4. Upgrade management-cluster plugin to `v0.28.0`
5. Upgrade management-cluster itself to newer TKG version with new plugin
6. At the end of the management-cluster upgrade, management-cluster plugin runs `tanzu plugin sync` through API to sync newer plugins
7. After the plugins gets installed, a warning `Warning, Masking commands for plugins "cluster, feature, kubernetes-release" because a core command or other plugin with that name already exists. ` is always shown with any Tanzu CLI command.

**Expected behavior**
The warning should not be shown.

**Steps to reproduce the bug / Relevant debug output**

**Output of `tanzu version`**
v0.90.0-alpha.1
**Environment where the bug was observed (cloud, OS, etc)**

### PR DESCRIPTION
**Pull request by anujc25**
### What this PR does / why we need it

**Issue:**
1. Install management-cluster v0.25.4 plugin with tanzu-cli v0.25.4.
2. Create management-cluster
3. Install independent Tanzu CLI v0.90.0-alpha.1
4. Upgrade management-cluster plugin to v0.28.0
5. Upgrade management-cluster itself to newer TKG version with new plugin
6. At the end of the management-cluster upgrade, management-cluster plugin runs tanzu plugin sync through API to sync newer plugins
7. After the plugins gets installed, a warning Warning, Masking commands for plugins "cluster, feature, kubernetes-release" because a core command or other plugin with that name already exists.  is always shown with any Tanzu CLI command.

This is happening because of the bug in the Tanzu CLI library for v0.28.0 and v0.29.0. The issue was fixed as part of #201 in the independent Tanzu CLI release. However, if old plugin runs tanzu plugin sync programmatically which has this bug present we still see this warning.

This PR tries to delete any incorrect plugin entries from the catalog cache to recover the CLI from showing the warning message.

### Which issue(s) this PR fixes

Fixes #312

### Describe testing done for PR
```
#### Install a plugin for which the target has been updated in the newer releases. (`` target to `kubernetes` target for `package` plugin
$ tanzu-0.25.4 plugin install package
Installing plugin 'package:v0.25.4'
✔  successfully installed 'package' plugin

$ tanzu-0.25.4 plugin list
  NAME                DESCRIPTION                                                        SCOPE       DISCOVERY               VERSION  STATUS
  cluster             Cluster Plugin For Kubernetes                                      Context     default-test-cluster-1  v0.25    not installed
  feature             Feature Plugin For Kubernetes                                      Context     default-test-cluster-1  v0.25    not installed
  kubernetes-release  KR Plugin For Kubernetes                                           Context     default-test-cluster-1  v0.25    not installed
  login               Login to the platform                                              Standalone  default                 v0.25.4  not installed
  management-cluster  Kubernetes management-cluster operations                           Standalone  default                 v0.25.4  not installed
  package             Tanzu package management                                           Standalone  default                 v0.25.4  installed
  pinniped-auth       Pinniped authentication operations (usually not directly invoked)  Standalone  default                 v0.25.4  not installed
  secret              Tanzu secret management                                            Standalone  default                 v0.25.4  not installed
  telemetry           Configure cluster-wide telemetry settings                          Standalone  default                 v0.25.4  not installed


#### Install the same `package` plugin with v0.28.0 version of Tanzu-CLI where the target of that plugin was updated to `kubernetes`
$ tanzu-0.28.0 plugin install package
ℹ  Installing plugin 'package:v0.28.0' with target 'kubernetes'
✔  successfully installed 'package' plugin


### After the installation of the package plugin any command run will show a warning as below
$ tanzu-0.28.0 plugin list
Warning, Masking commands for plugins "package" because a core command or other plugin with that name already exists.
Standalone Plugins
  NAME                DESCRIPTION                                                        TARGET      DISCOVERY  VERSION  STATUS
  isolated-cluster    isolated-cluster operations                                                    default    v0.28.0  not installed
  login               Login to the platform                                                          default    v0.28.0  not installed
  pinniped-auth       Pinniped authentication operations (usually not directly invoked)              default    v0.28.0  not installed
  management-cluster  Kubernetes management-cluster operations                           kubernetes  default    v0.28.0  not installed
  package             Tanzu package management                                           kubernetes  default    v0.25.4  installed
  secret              Tanzu secret management                                            kubernetes  default    v0.28.0  not installed
  telemetry           Configure cluster-wide telemetry settings                          kubernetes  default    v0.28.0  not installed


### This is because the old CLI allowed a new entry for the package 
### plugin to be added to the cache without removing the old entry. 
### This bug was fixed recently in the v0.90.0-alpha.0 release with https://github.com/vmware-tanzu/tanzu-cli/pull/201
### However, if the entry already exists and the user uses the `v0.90.0-alpha.2` CLI this is still an issue.
$ cat ~/.cache/tanzu/catalog.yaml
...
standAlonePlugins:
  package: /Users/anujc/Library/Application Support/tanzu-cli/package/v0.25.4
  package_kubernetes: /Users/anujc/Library/Application Support/tanzu-cli/package/v0.28.0_2602f8da6d2101d44dd4bbfb8905e231ed261baf5b529d435f6e52894a927f11_kubernetes


### THIS PR TRIES TO FIX THIS BY DELETING THE OLD INCORRECT ENTRIES FROM THE CATALOG WHEN THIS
### ISSUE GETS OBSERVED FOR THE FIRST TIME
### Using the New CLI with this Bug fix should not show any warning and should fix the catalog cache when any command
### Gets invoked
$ tz --help
Usage:
  tanzu [command]

Available command groups:
...


### Checking the catalog cache after running the above command to verify the cache was updated
$ cat ~/.cache/tanzu/catalog.yaml
...
standAlonePlugins:
    package_kubernetes: /Users/anujc/Library/Application Support/tanzu-cli/package/v0.28.0_2602f8da6d2101d44dd4bbfb8905e231ed261baf5b529d435f6e52894a927f11_kubernetes
```

### Release note

```release-note
Fix corrupt catalog cache issue when plugins were installed with old CLI
```

### CODE REVIEW

**Review by vuil — APPROVED** [review]
lgtm, nice update to still identify and log core command based overlap.

**Review by vuil — APPROVED** [review]
lgtm, nice update to still identify and log core command based overlap.

File: pkg/command/root.go [hunk 1]
```diff
@@ -209,6 +218,11 @@ func isStandalonePluginCommand(cmd *cobra.Command) bool {
 	return exists && scope == common.PluginScopeStandalone
 }
 
+func isPluginCommand(cmd *cobra.Command) bool {
+	t, exists := cmd.Annotations["type"]
+	return exists && t == "plugin"
```
Comment (marckhouzam) [inline pkg/command/root.go:223]: Nit: could you make "plugin" a constant?  That way we can ask the IDE to show us where that annotation is set.  Using a plain "plugin" string makes it a little more difficult to trace this logic.

File: pkg/command/root.go [hunk 2]
```diff
@@ -86,20 +88,27 @@ func NewRootCmd() (*cobra.Command, error) {
...
 		}
 	}
 
-	if len(maskedPlugins) > 0 {
-		fmt.Fprintf(os.Stderr, "Warning, Masking commands for plugins %q because a core command or other plugin with that name already exists. \n", strings.Join(maskedPlugins, ", "))
+	if len(maskedPluginsWithPluginOverlap) > 0 {
+		catalog.DeleteIncorrectPluginEntriesFromCatalog()
+	}
+	if len(maskedPluginsWithCoreCmdOverlap) > 0 {
+		fmt.Fprintf(os.Stderr, "Warning, Masking commands for plugins %q because a core command with that name already exists. \n", strings.Join(maskedPluginsWithCoreCmdOverlap, ", "))
```
Comment (marckhouzam) [inline pkg/command/root.go:111]: Since we are changing this, might as well fix the string:
```suggestion
		fmt.Fprintf(os.Stderr, "Warning, masking commands for plugins %q because a core command with that name already exists. \n", strings.Join(maskedPluginsWithCoreCmdOverlap, ", "))
```

**Review by marckhouzam — APPROVED** [review]
Just nits.
LGTM
