### PR TITLE
Delete entries using unknown target

### LINKED ISSUE #200: Global plugin may not replace previous installation
**Bug description**

If I install a plugin with a "global" target, it will not replace an existing installation of that plugin that used the "unknown" target.

**Expected behavior**

The "global" target and the "unknown" target should be considered the same when installing a plugin.

**Steps to reproduce the bug / Relevant debug output**

Installing a plugin using the "unknown" target followed by installing the same plugin using the "global" target:
```
$ tz plugin clean
[ok] successfully cleaned up all plugins
$ tz plugin install isolated-cluster --local ~/.config/tanzu-plugins/
[i] Installing plugin 'isolated-cluster:v0.29.0-dev'
[ok] successfully installed 'isolated-cluster' plugin
$ bin/tanzu plugin list
Standalone Plugins
  NAME              DESCRIPTION                                                       TARGET  VERSION      STATUS
  isolated-cluster  Prepopulating images/bundle for internet-restricted environments          v0.29.0-dev  installed
$ tz plugin install isolated-cluster
[i] Installing plugin 'isolated-cluster:v0.28.0' with target 'global'
[ok] successfully installed 'isolated-cluster' plugin
$ bin/tanzu plugin list
Warning, Masking commands for plugins "isolated-cluster" because a core command or other plugin with that name already exists.
Standalone Plugins
  NAME              DESCRIPTION                                                       TARGET  VERSION      STATUS
  isolated-cluster  Prepopulating images/bundle for internet-restricted environments          v0.29.0-dev  installed
  isolated-cluster  Prepopulating images/bundle for internet-restricted environments  global  v0.28.0      installed
```

Installing a plugin using the "global" target followed by installing the same plugin using the "unknown" target:
```
$ tz plugin clean
[ok] successfully cleaned up all plugins
$ tz plugin install isolated-cluster
[i] Installing plugin 'isolated-cluster:v9.9.9' with target 'global'
[ok] successfully installed 'isolated-cluster' plugin
$ tz plugin list
Standalone Plugins
  NAME              DESCRIPTION                     TARGET  VERSION  STATUS
  isolated-cluster  isolated-cluster functionality  global  v9.9.9   installed
$ tz plugin install isolated-cluster --local ~/.config/tanzu-plugins/
[i] Installing plugin 'isolated-cluster:v0.29.0-dev'
[ok] successfully installed 'isolated-cluster' plugin
$ tz plugin list
Warning, Masking commands for plugins "isolated-cluster" because a core command or other plugin with that name already exists.
Standalone Plugins
  NAME              DESCRIPTION                                                       TARGET  VERSION      STATUS
  isolated-cluster  Prepopulating images/bundle for internet-restricted environments          v0.29.0-dev  installed
  isolated-cluster  isolated-cluster functionality                                    global  v9.9.9       installed```

**Output of `tanzu version`**

sha: 88d710167

**Environment where the bug was observed (cloud, OS, etc)**

Locally

### PR DESCRIPTION
**Pull request by marckhouzam**
### What this PR does / why we need it

Plugins aimed at a "global" target (not "k8s" nor "tmc") use a target named "global", but used to use the unknown/unspecified target which was just the empty string.

If an plugin is installed with the "global" target, it now replaces any installation that uses the unknown target and vice versa.

### Which issue(s) this PR fixes

Fixes #200

### Describe testing done for PR
I repeated the two tests shown in #200 (as shown below) and confirmed only the last installation was shown.
I also verified that the catalog only contained the last installation info.

```
$ tz plugin clean
Warning, Masking commands for plugins "isolated-cluster" because a core command or other plugin with that name already exists.
[ok] successfully cleaned up all plugins
$ tz plugin install isolated-cluster --local ~/.config/tanzu-plugins/
[i] Installing plugin 'isolated-cluster:v0.29.0-dev'
[ok] successfully installed 'isolated-cluster' plugin
$ tz plugin list
Standalone Plugins
  NAME              DESCRIPTION                                                       TARGET  VERSION      STATUS
  isolated-cluster  Prepopulating images/bundle for internet-restricted environments          v0.29.0-dev  installed
$ tz plugin install isolated-cluster
[i] Installing plugin 'isolated-cluster:v9.9.9' with target 'global'
[ok] successfully installed 'isolated-cluster' plugin
$ tz plugin list
Standalone Plugins
  NAME              DESCRIPTION                     TARGET  VERSION  STATUS
  isolated-cluster  isolated-cluster functionality  global  v9.9.9   installed
$ tz plugin install isolated-cluster --local ~/.config/tanzu-plugins/
[i] Installing plugin 'isolated-cluster:v0.29.0-dev'
[ok] successfully installed 'isolated-cluster' plugin
$ tz plugin list
Standalone Plugins
  NAME              DESCRIPTION                                                       TARGET  VERSION      STATUS
  isolated-cluster  Prepopulating images/bundle for internet-restricted environments          v0.29.0-dev  installed
```

### Release note

```release-note

```

### CODE REVIEW

File: pkg/catalog/catalog.go [hunk 1]
```diff
@@ -71,9 +71,31 @@ func (c *ContextCatalog) Upsert(plugin *cli.PluginInfo) error {
 		c.sharedCatalog.IndexByName[pluginNameTarget] = append(c.sharedCatalog.IndexByName[pluginNameTarget], plugin.InstallationPath)
 	}
 
+	// The "unknown" target was previously used in two scenarios:
+	// 1- to represent the global target (>= v0.28)
```
Comment (anujc25) [inline pkg/catalog/catalog.go:75]: With `v0.90` of runtime, we do not support plugins built using an `unknown` target.

```suggestion
	// 1- to represent the global target (>= v0.28 and < v0.90)
```

**Review by anujc25 — COMMENTED** [review]
Just a nit. Looks good otherwise.

**Review by anujc25 — APPROVED** [review]
