### PR TITLE
Fix vcs status error by allowing passing in build go flags to plugin builder

### LINKED ISSUE #263: With upgrade to Go 1.19, Tanzu CLI Plugin Builder returns 'error obtaining VCS status' error when being built in Git submodule (buildweb gobuild)
**Bug description**

After I upgraded all my go modules to use go version 1.19, and when I try to run builder from a Git submodule, I get this error: 

```
building local repository at ./artifacts/plugins, v0.1.0, [all]
ðŸ¦ - building plugin at path "cmd/plugin/feature"
ðŸ¦ - running godep path "cmd/plugin/feature"
ðŸ¦$ /usr/local/go/bin/go mod download
ðŸ¦ - $ /usr/local/go/bin/go build -o /workspace/artifacts/plugins/linux/arm64/kubernetes/feature/v0.1.0/tanzu-feature-linux_arm64 -ldflags  -X 'github.com/vmware-tanzu/tanzu-plugin-runtime/plugin/buildinfo.Version=v0.1.0' -tags  ./.
ðŸ¦ - error: exit status 1
ðŸ¦ - output: error obtaining VCS status: exit status 128
 	Use -buildvcs=false to disable VCS stamping.
ðŸ¦ - error compiling plugin feature 
```

**Expected behavior**

I expect that plugins can be built from within a Git submodule using Go version 1.19 and above.

**Steps to reproduce the bug / Relevant debug output**

**Output of `tanzu version`**

**Environment where the bug was observed (cloud, OS, etc)**

### PR DESCRIPTION
**Pull request by codegold79**
### What this PR does / why we need it

This PR allows for the passing of Go flags to the `go build` command during the building of plugins using Tanzu Plugin Builder.

The reason I need it is because it will allow me to prevent a VCS status error that happens in our downstream build environment: 

```
building local repository at ./artifacts/plugins, v0.1.0, [all]
ðŸ¦ - building plugin at path "cmd/plugin/feature"
ðŸ¦ - running godep path "cmd/plugin/feature"
ðŸ¦$ /usr/local/go/bin/go mod download
ðŸ¦ - $ /usr/local/go/bin/go build -o /workspace/artifacts/plugins/linux/arm64/kubernetes/feature/v0.1.0/tanzu-feature-linux_arm64 -ldflags  -X 'github.com/vmware-tanzu/tanzu-plugin-runtime/plugin/buildinfo.Version=v0.1.0' -tags  ./.
ðŸ¦ - error: exit status 1
ðŸ¦ - output: error obtaining VCS status: exit status 128
 	Use -buildvcs=false to disable VCS stamping.
ðŸ¦ - error compiling plugin feature 
```

### Which issue(s) this PR fixes

Fixes #263 

### Describe testing done for PR

I ran `builder plugin build` with and without the `--goflags '-buildvcs=false'` and the plugins built as intended. 

I also tested passing in the argument in our downstream build environment, and it worked without giving the vcs status error.

To test the Makefile changes and multiple go flags, I have also successfully run the commands,
- make plugin-build
- make plugin-build PLUGIN_GO_FLAGS="-buildvcs=false"
- make plugin-build PLUGIN_GO_FLAGS="-buildvcs=false -a"

Here is the output from running the above commands: [2023-05-09_make-plugin-build-log.txt](https://github.com/vmware-tanzu/tanzu-cli/files/11435225/2023-05-09_make-plugin-build-log.txt)

### Release note

```release-note
Allow for passing go flags when building plugins.
```

### CODE REVIEW

File: cmd/plugin/builder/command/cli_compile.go [hunk 1]
```diff
@@ -327,14 +330,17 @@ type target struct {
...
+func (t target) build(targetPath, prefix, modPath, ldflags, tags, goflags string) error {
 	cmd := goCommand("build")
 
 	var commonArgs = []string{
 		"-ldflags", ldflags,
 		"-tags", tags,
 	}
 
+	if goflags != "" {
+		cmd.Args = append(cmd.Args, goflags)
```
Comment (marckhouzam) [inline cmd/plugin/builder/command/cli_compile.go:342]: I'm under the impression that as it is proposed, we would only be able to add a single goflag.  Say I want to add both `-buildvcs=false` and `-a`, I don't think I can.

Although we could allow for multiple `--goflags` flags, I think it would be simpler to accept multiple space-separated values for the single `--goflags` flag.
So, in the above line, you can probably just `strings.Split(goflags, " ")`

Then we should be able to do `tanzu builder plugin build --goflags "-buildvcs=false -a"`

**Review by marckhouzam — CHANGES_REQUESTED** [review]
Thanks @codegold79.  This improvement will give the builder plugin more flexibility 👍 
In that optic let's make sure the change is generic.  Please see one comment in-line.

Also, if you don't mind could you integrate this change into `plugin-tooling.mk` so that users can use the makefile and still add goflags?  I suggest:
- at the top, after the `PLUGIN_LD_FLAGS` variable, adding `PLUGIN_GO_FLAGS ?=` to set this new variable to the empty string if it is not provided by the user
- in the `plugin-build-%` make target, add the line `--goflags "$(PLUGIN_GO_FLAGS)" \`

Then, we will be able to call `make plugin-build-local PLUGIN_GO_FLAGS="-buildvcs=false -a"` to include extra goflags.

 And finally, make the exact same makefile changes in `cmd/plugin/builder/template/plugintemplates/plugin-tooling.mk.tmpl`

Thanks!

File: cmd/plugin/builder/command/cli_compile.go (hunk 1 above)
Comment (codegold79) [reply cmd/plugin/builder/command/cli_compile.go]: Great suggestion. I have applied it in the latest commit.

**Review by marckhouzam — APPROVED** [review]
Very nice! LGTM
Thanks @codegold79 !

cc @anujc25 @vuil

**Review by vuil — APPROVED** [review]
lgtm, thanks!

**Review by vuil — APPROVED** [review]
lgtm, thanks!
