### PR TITLE
Root-targeted plugins now include "global" plugins

### LINKED ISSUE #91: Plugins with "global" target cannot be invoked
**Bug description**

We recently added an explicit "global" target in https://github.com/vmware-tanzu/tanzu-plugin-runtime/pull/17.
And the builder plugin started using it in #73 

However, the CLI was not updated to consider the new "global" target to invoke global plugins.  This means the new builder plugin can no longer be invoked.

**Expected behavior**

The builder plugin should be invokable.

**Steps to reproduce the bug / Relevant debug output**

```
$ git checkout main
$ make build-all
[...]
$ tz plugin install builder --local ./artifacts-admin/darwin/amd64
ℹ  Installing plugin 'builder:v0.0.2-dev' with target 'global'
✔  successfully installed 'builder' plugin

$ tz builder -h
✖  unknown command "builder" for "tanzu"
```

**Output of `tanzu version`**

version: v0.0.2-dev
buildDate: 2023-03-05
sha: 46474c69b

**Environment where the bug was observed (cloud, OS, etc)**

Local

### PR DESCRIPTION
**Pull request by marckhouzam**
### What this PR does / why we need it

Allows to invoke plugins that use the new "global" target.  For example the `builder` plugin.
Without this, the latest version of the `builder` plugin cannot be invoked from the CLI.

### Which issue(s) this PR fixes

Fixes #91

### Describe testing done for PR

Before the PR:
```
$ git checkout main
$ make build-all
[...]
$ tz plugin install builder --local ./artifacts-admin/darwin/amd64
ℹ  Installing plugin 'builder:v0.0.2-dev' with target 'global'
✔  successfully installed 'builder' plugin

$ tz builder -h
✖  unknown command "builder" for "tanzu"
```
After the PR:
```
$ make build-all
[...]
$ tz plugin install builder --local ./artifacts-admin/darwin/amd64
ℹ  Installing plugin 'builder:v0.0.2-dev' with target 'global'
✔  successfully installed 'builder' plugin

$ tz builder -h
Build Tanzu components

Usage:
  tanzu builder [command]
[...]
```

### Release note

```release-note

```

### Additional information

I added unit test to verify that the correct targets where invokable.
This (of course 🙄 ) triggered some unexpected failures which I had to chase down.  This is why `manager.go` has a small fix.

### CODE REVIEW

File: pkg/cli/plugin_cmd.go [hunk 1]
```diff
@@ -26,6 +26,7 @@ func GetCmdForPlugin(p *PluginInfo) *cobra.Command {
 		DisableFlagParsing: true,
 		Annotations: map[string]string{
 			"group": string(p.Group),
+			"scope": p.Scope,
```
Comment (marckhouzam) [inline pkg/cli/plugin_cmd.go:29]: This was added to TF after we moved it to this repo:
https://github.com/vmware-tanzu/tanzu-framework/blob/8354312f13e95a96ccee234d3423ede33eeec09c/cli/core/pkg/cli/cmd.go#L31

File: pkg/pluginmanager/manager.go [hunk 2]
```diff
@@ -437,6 +437,7 @@ func DiscoveredFromPlugininfo(p *cli.PluginInfo) discovery.Discovered {
 		RecommendedVersion: p.Version,
 		Source:             p.Discovery,
 		SupportedVersions:  []string{p.Version},
+		Target:             p.Target,
```
Comment (marckhouzam) [inline pkg/pluginmanager/manager.go:440]: The target was not being copied from one struct to the other, which caused some unexpected failures in the new unit tests.

**Review by anujc25 — APPROVED** [review]
LGTM. Thank for the fix.
