### PR TITLE
Sync plugins after a "context use"

### LINKED ISSUE #51: "tanzu context use" does not sync plugin from context
**Bug description**

When calling `tanzu context use <context>` a new context becomes active.  I would expect the context-plugins to be synched from this newly active context.  This does not seem to happen.

Note that the legacy `tanzu login --server <context>` which is the deprecated form of `tanzu context use`, does trigger a sync.  This confirms it is a bug that `tanzu context use` does not behave the same.

**Expected behavior**

`tanzu context use` should trigger a plugin sync for the newly active context.

**Steps to reproduce the bug / Relevant debug output**

```
cd tanzu-cli
git checkout main
make build

# Remove current config
rm ~/.config/tanzu/config*

# Create a k8s context, the plugins will sync
tz context create --name k3d --kubecontext k3d-k3s-default --kubeconfig /Users/kmarc/.config/k3d/k3s-default/kubeconfig.yaml
# Create a second k8s context, the plugins will sync from that new context
tz context create --name k3d2 --kubecontext k3d-k3s-default --kubeconfig /Users/kmarc/.config/k3d/k3s-default/kubeconfig.yaml

# Use the first k8s context, the plugins don't sync => BUG
tz context use k3d

# Use the tz login form instead, plugins do sync
tz login --server k3d
```

**Output of `tanzu version`**

version: v0.0.1-dev
buildDate: 2023-01-30
sha: b1709b3c

**Environment where the bug was observed (cloud, OS, etc)**

Locally

### PR DESCRIPTION
**Pull request by marckhouzam**
### What this PR does / why we need it

This PR triggers a plugin sync when a "tz context use ..." succeeds.  When the user switches to a new context, they should get the corresponding plugins.

### Which issue(s) this PR fixes

Fixes #51 

### Describe testing done for PR

I first tested with `main` and reproduced the bug.
Then I tested with the PR and the Central Repo feature enabled.
```
$ rm ~/.config/tanzu/config*
$ tz plugin clean
✔  successfully cleaned up all plugins
$ export TANZU_CLI_PRE_RELEASE_REPO_IMAGE=localhost:9876/tanzu-cli/plugins/central:small
$ make start-test-central-repo
[...]
$ tz config set features.global.central-repository true
$
# Create the first context
$ tz context create --name tmc-unstable --endpoint unstable.tmc-dev.cloud.vmware.com --staging

✔  successfully created a TMC context
ℹ  Checking for required plugins...
ℹ  Installing plugin 'kubernetes-release:v9.9.9' with target 'kubernetes'
ℹ  Installing plugin 'cluster:v9.9.9' with target 'kubernetes'
ℹ  Installing plugin 'feature:v9.9.9' with target 'kubernetes'
ℹ  Installing plugin 'policy:v0.0.1' with target 'mission-control'
ℹ  Installing plugin 'audit:v0.0.1' with target 'mission-control'
^C
# Create a second context
$ tz context create --name tmc-unstable2 --endpoint unstable.tmc-dev.cloud.vmware.com --staging

✔  successfully created a TMC context
ℹ  Checking for required plugins...
ℹ  Installing plugin 'kubernetes-release:v9.9.9' with target 'kubernetes'
ℹ  Installing plugin 'cluster:v9.9.9' with target 'kubernetes'
ℹ  Installing plugin 'feature:v9.9.9' with target 'kubernetes'
^C
$ tz context list
Target:  kubernetes
  NAME  ISACTIVE  ENDPOINT  KUBECONFIGPATH  KUBECONTEXT
Target:  mission-control
  NAME           ISACTIVE  ENDPOINT
  tmc-unstable   false     unstable.tmc-dev.cloud.vmware.com:443
  tmc-unstable2  true      unstable.tmc-dev.cloud.vmware.com:443

# Switch context and make sure the plugins get synched
$ tz context use tmc-unstable
ℹ  Checking for required plugins...
ℹ  Installing plugin 'account:v0.0.1' with target 'mission-control'
ℹ  Installing plugin 'audit:v0.0.1' with target 'mission-control'
ℹ  Installing plugin 'continuousdelivery:v0.0.1' with target 'mission-control'
ℹ  Installing plugin 'policy:v0.0.1' with target 'mission-control'
ℹ  Installing plugin 'apply:v0.0.1' with target 'mission-control'
^C

# Switch again
$ tz context use tmc-unstable2
ℹ  Checking for required plugins...
ℹ  Installing plugin 'helm:v0.0.1' with target 'mission-control'
ℹ  Installing plugin 'apply:v0.0.1' with target 'mission-control'
ℹ  Installing plugin 'integration:v0.0.1' with target 'mission-control'
ℹ  Installing plugin 'iam:v0.0.1' with target 'mission-control'
ℹ  Installing plugin 'tanzupackage:v0.0.1' with target 'mission-control'
ℹ  Installing plugin 'account:v0.0.1' with target 'mission-control'
```
Then I tested with the PR and the Central Repo feature disabled.
```
$ tz config set features.global.central-repository false
$ tz context list
Target:  kubernetes
  NAME  ISACTIVE  ENDPOINT  KUBECONFIGPATH  KUBECONTEXT
Target:  mission-control
  NAME           ISACTIVE  ENDPOINT
  tmc-unstable   false     unstable.tmc-dev.cloud.vmware.com:443
  tmc-unstable2  true      unstable.tmc-dev.cloud.vmware.com:443
$ tz context use tmc-unstable
ℹ  Checking for required plugins...
ℹ  Installing plugin 'management-cluster:v0.0.1' with target 'mission-control'
^C
$ tz context use tmc-unstable2
ℹ  Checking for required plugins...
ℹ  Installing plugin 'account:v0.0.1' with target 'mission-control'
^C
```

### Release note

```release-note
"tanzu context use <contextName>" will now trigger the synchronization of plugins.
```

#### Special notes for your reviewer

- adding a unit test for this fix would require some substantial modifications as the pluginManager cannot yet be stubbed.

### CODE REVIEW

File: hack/central-repo/upload-plugins.sh [hunk 1]
```diff
@@ -125,7 +125,8 @@ addPlugin() {
 
 k8sPlugins=(cluster feature management-cluster package secret telemetry kubernetes-release)
 tmcPlugins=(account apply audit cluster clustergroup data-protection ekscluster events iam 
-            inspection integration management-cluster policy workspace)
+            inspection integration management-cluster policy workspace helm secret 
+            continuousdelivery tanzupackage)
```
Comment (marckhouzam) [inline hack/central-repo/upload-plugins.sh:129]: These are new plugins added by the TMC endpoint.  I'm adding them to the docker test central repo so that a plugin sync can find all plugins and succeed.

File: pkg/pluginmanager/manager.go [hunk 2]
```diff
@@ -759,14 +759,17 @@ func SyncPlugins() error {
 		// Note: to install all plugins for a specific product, plugin groups will
 		// need to be used.
 		plugins, err = DiscoverServerPlugins()
+		if err != nil {
+			return err
+		}
```
Comment (marckhouzam) [inline pkg/pluginmanager/manager.go:764]: The error was mistakenly being ignored before.
This should be a separate PR, but in the interest of time, I'm cheating a bit.

Comment (anujc25) [reply pkg/pluginmanager/manager.go:872]: Thanks for fixing this. 👍

Comment (anujc25) [reply pkg/pluginmanager/manager.go:872]: Thanks for fixing this. 👍

**Review by anujc25 — APPROVED** [review]
LGTM.
