### PR TITLE
Do not show command masked warning for `login` plugin

### LINKED ISSUE #191: Poor UX when old login plugin is installed user installs new CLI
**Bug description**

Steps to reproduce:-

Install legacy tanzu cli v0.28
tanzu plugin install login
install new tanzu cli v0.81.1
Run any tanzu command will prompt the warning
```
root@6988f06c77b9 /app# tanzu version
Warning, Masking commands for plugins "login" because a core command or other plugin with that name already exists. 
version: v0.81.1
buildDate: 2023-04-05
sha: 4212c43f
root@6988f06c77b9 /app# 
```

Note: Even if using the new tanzu cli with the old login plugin which is installed by the previous tanzu the warning message is shown

**Expected behavior**

**Steps to reproduce the bug / Relevant debug output**

**Output of `tanzu version`**

**Environment where the bug was observed (cloud, OS, etc)**

### PR DESCRIPTION
**Pull request by anujc25**
### What this PR does / why we need it

- Do not show command masked warning for the `login` plugin
- As the `login` plugin is now part of the core Tanzu CLI command and not a plugin anymore, skip the `login` plugin from adding it to the maskedPlugins array to avoid the warning message from getting shown to the user on each command invocation.

### Which issue(s) this PR fixes

Fixes #191

### Describe testing done for PR

- Install plugins with old CLI
```
/t/4 $ tanzu-0.28.0 plugin sync
ℹ  Checking for required plugins...
ℹ  Installing plugin 'management-cluster:v0.28.0' with target 'kubernetes'
ℹ  Installing plugin 'package:v0.28.0' with target 'kubernetes'
ℹ  Installing plugin 'pinniped-auth:v0.28.0'

ℹ  Installing plugin 'secret:v0.28.0' with target 'kubernetes'
ℹ  Installing plugin 'telemetry:v0.28.0' with target 'kubernetes'
ℹ  Installing plugin 'isolated-cluster:v0.28.0'
ℹ  Installing plugin 'login:v0.28.0'
ℹ  Successfully installed all required plugins
✔  Done
```

- Run a command with a new CLI WITHOUT bug fix
```
$ tz version
Warning, Masking commands for plugins "login" because a core command or other plugin with that name already exists.
version: v0.81.1
buildDate: 2023-04-06
sha: 73a4c10d-dirty
```

- Run a command with a new CLI WITH bug fix
```
$ tz version
version: v0.81.1
buildDate: 2023-04-06
sha: d3580d4e
```

### Release note

```release-note

```

### CODE REVIEW

File: pkg/command/root.go [hunk 1]
```diff
@@ -107,7 +107,12 @@ func NewRootCmd() (*cobra.Command, error) {
 				rootCmd.RemoveCommand(matchedCmd)
 				rootCmd.AddCommand(cmd)
 			} else {
-				maskedPlugins = append(maskedPlugins, plugins[i].Name)
+				// As the `login` plugin is now part of the core Tanzu CLI command and not a plugin
+				// anymore, skip the `login` plugin from adding it to the markedPlugins array to avoid
```
Comment (vuil) [inline pkg/command/root.go:111]: nit: maskedPlugins, and there is extra space in the comment in the next line.
otherwise lgtm

**Review by vuil — APPROVED** [review]
